XConsultingAgencyWeb/src/java/jpa/entities/Client.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpa.entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author x-doggy
 */
@Entity
@Table(name = "CLIENT")
@XmlRootElement
@NamedQueries({
	@NamedQuery(name = "Client.findAll", query = "SELECT c FROM Client c")
	, @NamedQuery(name = "Client.findByClientName", query = "SELECT c FROM Client c WHERE c.clientPK.clientName = :clientName")
	, @NamedQuery(name = "Client.findByClientDepartmentNumber", query = "SELECT c FROM Client c WHERE c.clientPK.clientDepartmentNumber = :clientDepartmentNumber")
	, @NamedQuery(name = "Client.findByContactEmail", query = "SELECT c FROM Client c WHERE c.contactEmail = :contactEmail")
	, @NamedQuery(name = "Client.findByContactPassword", query = "SELECT c FROM Client c WHERE c.contactPassword = :contactPassword")})
public class Client implements Serializable {

	private static final long serialVersionUID = 1L;
	@EmbeddedId
	protected ClientPK clientPK;
	@Size(max = 50)
  @Column(name = "CONTACT_EMAIL")
	private String contactEmail;
	@Size(max = 50)
  @Column(name = "CONTACT_PASSWORD")
	private String contactPassword;
	@OneToMany(mappedBy = "client")
	private Collection<Recruiter> recruiterCollection;
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "client")
	private Collection<Project> projectCollection;
	@JoinColumn(name = "BILLING_ADDRESS", referencedColumnName = "ADDRESS_ID")
  @OneToOne(optional = false)
	private Address billingAddress;

	public Client() {
	}

	public Client(ClientPK clientPK) {
		this.clientPK = clientPK;
	}

	public Client(String clientName, short clientDepartmentNumber) {
		this.clientPK = new ClientPK(clientName, clientDepartmentNumber);
	}

	public ClientPK getClientPK() {
		return clientPK;
	}

	public void setClientPK(ClientPK clientPK) {
		this.clientPK = clientPK;
	}

	public String getContactEmail() {
		return contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getContactPassword() {
		return contactPassword;
	}

	public void setContactPassword(String contactPassword) {
		this.contactPassword = contactPassword;
	}

	@XmlTransient
	public Collection<Recruiter> getRecruiterCollection() {
		return recruiterCollection;
	}

	public void setRecruiterCollection(Collection<Recruiter> recruiterCollection) {
		this.recruiterCollection = recruiterCollection;
	}

	@XmlTransient
	public Collection<Project> getProjectCollection() {
		return projectCollection;
	}

	public void setProjectCollection(Collection<Project> projectCollection) {
		this.projectCollection = projectCollection;
	}

	public Address getBillingAddress() {
		return billingAddress;
	}

	public void setBillingAddress(Address billingAddress) {
		this.billingAddress = billingAddress;
	}

	@Override
	public int hashCode() {
		int hash = 0;
		hash += (clientPK != null ? clientPK.hashCode() : 0);
		return hash;
	}

	@Override
	public boolean equals(Object object) {
		// TODO: Warning - this method won't work in the case the id fields are not set
		if (!(object instanceof Client)) {
			return false;
		}
		Client other = (Client) object;
		if ((this.clientPK == null && other.clientPK != null) || (this.clientPK != null && !this.clientPK.equals(other.clientPK))) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "jpa.entities.Client[ clientPK=" + clientPK + " ]";
	}
	
}

XConsultingAgencyWeb/src/java/jsf/ClientController.java
package jsf;

import jpa.entities.Client;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.ClientFacade;

import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean (name="clientController")
@SessionScoped
public class ClientController {

    private Client current;
    private DataModel items = null;
    @EJB private jpa.session.ClientFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public ClientController() {
    }

    public Client getSelected() {
        if (current == null) {
            current = new Client();
            selectedItemIndex = -1;
        }
        return current;
    }

    private ClientFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem()+getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Client)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Client();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("ClientCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Client)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("ClientUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Client)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("ClientDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count-1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex+1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass=Client.class)
    public static class ClientControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ClientController controller = (ClientController)facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "clientController");
            return controller.ejbFacade.find(getKey(value));
        }

        jpa.entities.ClientPK getKey(String value) {
            jpa.entities.ClientPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new jpa.entities.ClientPK();
            key.setClientName(values[0]);
            key.setClientDepartmentNumber(Short.parseShort(values[1]));
            return key;
        }

        String getStringKey(jpa.entities.ClientPK value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value.getClientName());
            sb.append(SEPARATOR);
            sb.append(value.getClientDepartmentNumber());
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Client) {
                Client o = (Client) object;
                return getStringKey(o.getClientPK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: "+ClientController.class.getName());
            }
        }

    }

}

XConsultingAgencyWeb/web/client/Create.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateClientTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateClientLabel_clientPK_clientDepartmentNumber}" for="clientPK.clientDepartmentNumber" />
                    <h:inputText id="clientPK.clientDepartmentNumber" value="#{clientController.selected.clientPK.clientDepartmentNumber}" title="#{bundle.CreateClientTitle_clientPK_clientDepartmentNumber}" required="true" requiredMessage="#{bundle.CreateClientRequiredMessage_clientPK_clientDepartmentNumber}"/>
                    <h:outputLabel value="#{bundle.CreateClientLabel_clientPK_clientName}" for="clientPK.clientName" />
                    <h:inputText id="clientPK.clientName" value="#{clientController.selected.clientPK.clientName}" title="#{bundle.CreateClientTitle_clientPK_clientName}" required="true" requiredMessage="#{bundle.CreateClientRequiredMessage_clientPK_clientName}"/>
                    <h:outputLabel value="#{bundle.CreateClientLabel_contactEmail}" for="contactEmail" />
                    <h:inputText id="contactEmail" value="#{clientController.selected.contactEmail}" title="#{bundle.CreateClientTitle_contactEmail}" />
                    <h:outputLabel value="#{bundle.CreateClientLabel_contactPassword}" for="contactPassword" />
                    <h:inputText id="contactPassword" value="#{clientController.selected.contactPassword}" title="#{bundle.CreateClientTitle_contactPassword}" />
                    <h:outputLabel value="#{bundle.CreateClientLabel_billingAddress}" for="billingAddress" />
                    <h:selectOneMenu id="billingAddress" value="#{clientController.selected.billingAddress}" title="#{bundle.CreateClientTitle_billingAddress}" required="true" requiredMessage="#{bundle.CreateClientRequiredMessage_billingAddress}">
                        <f:selectItems value="#{addressController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{clientController.create}" value="#{bundle.CreateClientSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{clientController.prepareList}" value="#{bundle.CreateClientShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.CreateClientIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

XConsultingAgencyWeb/web/client/Edit.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditClientTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditClientLabel_clientPK_clientDepartmentNumber}" for="clientPK.clientDepartmentNumber" />
                    <h:inputText id="clientPK.clientDepartmentNumber" value="#{clientController.selected.clientPK.clientDepartmentNumber}" title="#{bundle.EditClientTitle_clientPK_clientDepartmentNumber}" required="true" requiredMessage="#{bundle.EditClientRequiredMessage_clientPK_clientDepartmentNumber}"/>
                    <h:outputLabel value="#{bundle.EditClientLabel_clientPK_clientName}" for="clientPK.clientName" />
                    <h:inputText id="clientPK.clientName" value="#{clientController.selected.clientPK.clientName}" title="#{bundle.EditClientTitle_clientPK_clientName}" required="true" requiredMessage="#{bundle.EditClientRequiredMessage_clientPK_clientName}"/>
                    <h:outputLabel value="#{bundle.EditClientLabel_contactEmail}" for="contactEmail" />
                    <h:inputText id="contactEmail" value="#{clientController.selected.contactEmail}" title="#{bundle.EditClientTitle_contactEmail}" />
                    <h:outputLabel value="#{bundle.EditClientLabel_contactPassword}" for="contactPassword" />
                    <h:inputText id="contactPassword" value="#{clientController.selected.contactPassword}" title="#{bundle.EditClientTitle_contactPassword}" />
                    <h:outputLabel value="#{bundle.EditClientLabel_billingAddress}" for="billingAddress" />
                    <h:selectOneMenu id="billingAddress" value="#{clientController.selected.billingAddress}" title="#{bundle.EditClientTitle_billingAddress}" required="true" requiredMessage="#{bundle.EditClientRequiredMessage_billingAddress}">
                        <f:selectItems value="#{addressController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{clientController.update}" value="#{bundle.EditClientSaveLink}"/>
                <br />
                <br />
                <h:commandLink action="View" value="#{bundle.EditClientViewLink}" immediate="true"/>
                <br />
                <h:commandLink action="#{clientController.prepareList}" value="#{bundle.EditClientShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.EditClientIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

XConsultingAgencyWeb/web/client/List.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListClientTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
        <h:form styleClass="jsfcrud_list_form">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:outputText escape="false" value="#{bundle.ListClientEmpty}" rendered="#{clientController.items.rowCount == 0}"/>
            <h:panelGroup rendered="#{clientController.items.rowCount > 0}">
                <h:outputText value="#{clientController.pagination.pageFirstItem + 1}..#{clientController.pagination.pageLastItem + 1}/#{clientController.pagination.itemsCount}"/>&nbsp;
                <h:commandLink action="#{clientController.previous}" value="#{bundle.Previous} #{clientController.pagination.pageSize}" rendered="#{clientController.pagination.hasPreviousPage}"/>&nbsp;
                <h:commandLink action="#{clientController.next}" value="#{bundle.Next} #{clientController.pagination.pageSize}" rendered="#{clientController.pagination.hasNextPage}"/>&nbsp;
                <h:dataTable value="#{clientController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListClientTitle_clientPK_clientDepartmentNumber}"/>
                        </f:facet>
                        <h:outputText value="#{item.clientPK.clientDepartmentNumber}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListClientTitle_clientPK_clientName}"/>
                        </f:facet>
                        <h:outputText value="#{item.clientPK.clientName}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListClientTitle_contactEmail}"/>
                        </f:facet>
                        <h:outputText value="#{item.contactEmail}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListClientTitle_contactPassword}"/>
                        </f:facet>
                        <h:outputText value="#{item.contactPassword}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListClientTitle_billingAddress}"/>
                        </f:facet>
                        <h:outputText value="#{item.billingAddress}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="&nbsp;"/>
                        </f:facet>
                        <h:commandLink action="#{clientController.prepareView}" value="#{bundle.ListClientViewLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{clientController.prepareEdit}" value="#{bundle.ListClientEditLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{clientController.destroy}" value="#{bundle.ListClientDestroyLink}"/>
                    </h:column>
                </h:dataTable>
            </h:panelGroup>
            <br />
            <h:commandLink action="#{clientController.prepareCreate}" value="#{bundle.ListClientCreateLink}"/>
            <br />
            <br />
            <h:commandLink value="#{bundle.ListClientIndexLink}" action="/index" immediate="true" />
        </h:form>
        </ui:define>
    </ui:composition>

</html>

XConsultingAgencyWeb/web/client/View.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewClientTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewClientLabel_clientPK_clientDepartmentNumber}"/>
                    <h:outputText value="#{clientController.selected.clientPK.clientDepartmentNumber}" title="#{bundle.ViewClientTitle_clientPK_clientDepartmentNumber}"/>
                    <h:outputText value="#{bundle.ViewClientLabel_clientPK_clientName}"/>
                    <h:outputText value="#{clientController.selected.clientPK.clientName}" title="#{bundle.ViewClientTitle_clientPK_clientName}"/>
                    <h:outputText value="#{bundle.ViewClientLabel_contactEmail}"/>
                    <h:outputText value="#{clientController.selected.contactEmail}" title="#{bundle.ViewClientTitle_contactEmail}"/>
                    <h:outputText value="#{bundle.ViewClientLabel_contactPassword}"/>
                    <h:outputText value="#{clientController.selected.contactPassword}" title="#{bundle.ViewClientTitle_contactPassword}"/>
                    <h:outputText value="#{bundle.ViewClientLabel_billingAddress}"/>
                    <h:outputText value="#{clientController.selected.billingAddress}" title="#{bundle.ViewClientTitle_billingAddress}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{clientController.destroyAndView}" value="#{bundle.ViewClientDestroyLink}"/>
                <br />
                <br />
                <h:commandLink action="Edit" value="#{bundle.ViewClientEditLink}"/>
                <br />
                <h:commandLink action="#{clientController.prepareCreate}" value="#{bundle.ViewClientCreateLink}" />
                <br />
                <h:commandLink action="#{clientController.prepareList}" value="#{bundle.ViewClientShowAllLink}"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.ViewClientIndexLink}" action="/index" immediate="true" />

            </h:form>
        </ui:define>
    </ui:composition>

</html>